"""add description to submodules

Revision ID: d47aff39e7ad
Revises: 951e0445379d
Create Date: 2026-04-06 02:11:55.298715

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'd47aff39e7ad'
down_revision: Union[str, None] = '951e0445379d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('global_permissions', 'deleted_at')
    op.drop_column('global_permissions', 'is_deleted')
    op.drop_constraint('uq_module_role_slug', 'module_roles', type_='unique')
    op.drop_constraint('module_roles_module_id_fkey', 'module_roles', type_='foreignkey')
    op.create_foreign_key(None, 'module_roles', 'modules', ['module_id'], ['id'], ondelete='RESTRICT')
    op.drop_constraint('uq_submodule_permission_slug', 'submodule_permissions', type_='unique')
    op.drop_constraint('submodule_permissions_submodule_id_fkey', 'submodule_permissions', type_='foreignkey')
    op.create_foreign_key(None, 'submodule_permissions', 'submodules', ['submodule_id'], ['id'], ondelete='RESTRICT')
    op.drop_column('submodule_permissions', 'deleted_at')
    op.drop_column('submodule_permissions', 'is_deleted')
    op.drop_constraint('uq_submodule_module_slug', 'submodules', type_='unique')
    op.drop_constraint('submodules_module_id_fkey', 'submodules', type_='foreignkey')
    op.create_foreign_key(None, 'submodules', 'modules', ['module_id'], ['id'], ondelete='RESTRICT')
    op.alter_column('user_module_accesses', 'role_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.drop_constraint('user_module_accesses_role_id_fkey', 'user_module_accesses', type_='foreignkey')
    op.create_foreign_key(None, 'user_module_accesses', 'module_roles', ['role_id'], ['id'], ondelete='RESTRICT')
    op.drop_constraint('users_matricula_key', 'users', type_='unique')
    op.drop_index('ix_users_matricula', table_name='users')
    op.create_index(op.f('ix_users_matricula'), 'users', ['matricula'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_matricula'), table_name='users')
    op.create_index('ix_users_matricula', 'users', ['matricula'], unique=False)
    op.create_unique_constraint('users_matricula_key', 'users', ['matricula'])
    op.drop_constraint(None, 'user_module_accesses', type_='foreignkey')
    op.create_foreign_key('user_module_accesses_role_id_fkey', 'user_module_accesses', 'module_roles', ['role_id'], ['id'], ondelete='CASCADE')
    op.alter_column('user_module_accesses', 'role_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.drop_constraint(None, 'submodules', type_='foreignkey')
    op.create_foreign_key('submodules_module_id_fkey', 'submodules', 'modules', ['module_id'], ['id'], ondelete='CASCADE')
    op.create_unique_constraint('uq_submodule_module_slug', 'submodules', ['module_id', 'slug'])
    op.add_column('submodule_permissions', sa.Column('is_deleted', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.add_column('submodule_permissions', sa.Column('deleted_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'submodule_permissions', type_='foreignkey')
    op.create_foreign_key('submodule_permissions_submodule_id_fkey', 'submodule_permissions', 'submodules', ['submodule_id'], ['id'], ondelete='CASCADE')
    op.create_unique_constraint('uq_submodule_permission_slug', 'submodule_permissions', ['submodule_id', 'slug'])
    op.drop_constraint(None, 'module_roles', type_='foreignkey')
    op.create_foreign_key('module_roles_module_id_fkey', 'module_roles', 'modules', ['module_id'], ['id'], ondelete='CASCADE')
    op.create_unique_constraint('uq_module_role_slug', 'module_roles', ['module_id', 'slug'])
    op.add_column('global_permissions', sa.Column('is_deleted', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.add_column('global_permissions', sa.Column('deleted_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
