"""add_is_locked_cache_to_users

Revision ID: e1642a0e0227
Revises: e99cf1bc4cf6
Create Date: 2026-04-19 05:19:55.602060

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e1642a0e0227'
down_revision: Union[str, None] = 'e99cf1bc4cf6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('is_locked', sa.Boolean(), nullable=False, server_default='false'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'is_locked')
    # ### end Alembic commands ###
