"""add control_cambios_etapas

Revision ID: 1a6055e9022a
Revises: 5c0967de0571
Create Date: 2026-09-29 20:22:20.074544

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '1a6055e9022a'
down_revision: Union[str, None] = '5c0967de0571'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('control_cambios_etapas',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('incident_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('etapa', sa.String(length=30), nullable=False),
    sa.Column('resultado', sa.String(length=30), nullable=True),
    sa.Column('datos', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('documento_object_key', sa.String(length=500), nullable=True),
    sa.Column('anexos', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('realizado_por', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('realizado_por_nombre', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['incident_id'], ['incidents.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_control_cambios_etapas_incident_id'), 'control_cambios_etapas', ['incident_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_control_cambios_etapas_incident_id'), table_name='control_cambios_etapas')
    op.drop_table('control_cambios_etapas')
    # ### end Alembic commands ###
