"""add assigned_at to incidents

Revision ID: 1ae5444f3133
Revises: e31e3edfb865
Create Date: 2026-09-16 01:03:32.999885

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1ae5444f3133'
down_revision: Union[str, None] = 'e31e3edfb865'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('incidents', sa.Column('assigned_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('incidents', 'assigned_at')
    # ### end Alembic commands ###
