"""add cdc prioritization fields

Revision ID: 2b284ada4d9e
Revises: 1a6055e9022a
Create Date: 2026-09-29 20:47:54.473501

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2b284ada4d9e'
down_revision: Union[str, None] = '1a6055e9022a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('control_cambios_detalle', sa.Column('prioridad', sa.String(length=10), nullable=True))
    op.add_column('control_cambios_detalle', sa.Column('impacto_confirmado', sa.String(length=10), nullable=True))
    op.add_column('control_cambios_detalle', sa.Column('fecha_compromiso', sa.Date(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('control_cambios_detalle', 'fecha_compromiso')
    op.drop_column('control_cambios_detalle', 'impacto_confirmado')
    op.drop_column('control_cambios_detalle', 'prioridad')
    # ### end Alembic commands ###
