"""add control de accesos tables

Revision ID: 4e832b89cab4
Revises: f6b4d2a8c1e3
Create Date: 2026-09-30 22:20:05.388622

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '4e832b89cab4'
down_revision: Union[str, None] = 'f6b4d2a8c1e3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('acc_formatos',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('clave', sa.String(length=30), nullable=False),
    sa.Column('nombre', sa.String(length=120), nullable=False),
    sa.Column('system_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('severity_id', sa.UUID(as_uuid=False), nullable=True),
    sa.Column('admin_user_id', sa.UUID(as_uuid=False), nullable=True),
    sa.Column('admin_nombre', sa.String(length=255), nullable=True),
    sa.Column('activo', sa.Boolean(), nullable=False),
    sa.Column('orden', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['severity_id'], ['ticket_severities.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['system_id'], ['ticket_systems.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('clave')
    )
    op.create_table('acc_cuentas',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('formato_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('usuario_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('usuario_nombre', sa.String(length=255), nullable=False),
    sa.Column('estado', sa.String(length=15), nullable=False),
    sa.Column('usuario_asignado', sa.String(length=80), nullable=True),
    sa.Column('fecha_alta', sa.Date(), nullable=True),
    sa.Column('fecha_baja', sa.Date(), nullable=True),
    sa.Column('vigencia_hasta', sa.Date(), nullable=True),
    sa.Column('accesos', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['formato_id'], ['acc_formatos.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('formato_id', 'usuario_id', name='uq_acc_cuenta_usuario')
    )
    op.create_index(op.f('ix_acc_cuentas_formato_id'), 'acc_cuentas', ['formato_id'], unique=False)
    op.create_index(op.f('ix_acc_cuentas_usuario_id'), 'acc_cuentas', ['usuario_id'], unique=False)
    op.create_table('acc_formato_empresas',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('formato_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('company_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('orden', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['formato_id'], ['acc_formatos.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('formato_id', 'company_id', name='uq_acc_formato_empresa')
    )
    op.create_index(op.f('ix_acc_formato_empresas_formato_id'), 'acc_formato_empresas', ['formato_id'], unique=False)
    op.create_table('acc_formato_modulos',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('formato_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('nombre', sa.String(length=120), nullable=False),
    sa.Column('exclusivo_admin', sa.Boolean(), nullable=False),
    sa.Column('orden', sa.Integer(), nullable=False),
    sa.Column('activo', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['formato_id'], ['acc_formatos.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_acc_formato_modulos_formato_id'), 'acc_formato_modulos', ['formato_id'], unique=False)
    op.create_table('acc_modulo_perfiles',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('modulo_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('nombre', sa.String(length=80), nullable=False),
    sa.Column('orden', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['modulo_id'], ['acc_formato_modulos.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_acc_modulo_perfiles_modulo_id'), 'acc_modulo_perfiles', ['modulo_id'], unique=False)
    op.create_table('acc_modulo_rutinas',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('modulo_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('nombre', sa.String(length=150), nullable=False),
    sa.Column('orden', sa.Integer(), nullable=False),
    sa.Column('activo', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['modulo_id'], ['acc_formato_modulos.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_acc_modulo_rutinas_modulo_id'), 'acc_modulo_rutinas', ['modulo_id'], unique=False)
    op.create_table('acc_solicitudes',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('incident_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('formato_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('cuenta_id', sa.UUID(as_uuid=False), nullable=True),
    sa.Column('movimiento', sa.String(length=15), nullable=False),
    sa.Column('datos', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('pdf_object_key', sa.String(length=500), nullable=True),
    sa.Column('metodo_firma', sa.String(length=15), nullable=True),
    sa.Column('estado_firma', sa.String(length=20), nullable=True),
    sa.Column('docusign_envelope_id', sa.String(length=100), nullable=True),
    sa.Column('firmado_object_key', sa.String(length=500), nullable=True),
    sa.Column('usuario_asignado', sa.String(length=80), nullable=True),
    sa.Column('fecha_alta', sa.Date(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['cuenta_id'], ['acc_cuentas.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['formato_id'], ['acc_formatos.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['incident_id'], ['incidents.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('incident_id')
    )
    op.create_index(op.f('ix_acc_solicitudes_cuenta_id'), 'acc_solicitudes', ['cuenta_id'], unique=False)
    op.create_index(op.f('ix_acc_solicitudes_formato_id'), 'acc_solicitudes', ['formato_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_acc_solicitudes_formato_id'), table_name='acc_solicitudes')
    op.drop_index(op.f('ix_acc_solicitudes_cuenta_id'), table_name='acc_solicitudes')
    op.drop_table('acc_solicitudes')
    op.drop_index(op.f('ix_acc_modulo_rutinas_modulo_id'), table_name='acc_modulo_rutinas')
    op.drop_table('acc_modulo_rutinas')
    op.drop_index(op.f('ix_acc_modulo_perfiles_modulo_id'), table_name='acc_modulo_perfiles')
    op.drop_table('acc_modulo_perfiles')
    op.drop_index(op.f('ix_acc_formato_modulos_formato_id'), table_name='acc_formato_modulos')
    op.drop_table('acc_formato_modulos')
    op.drop_index(op.f('ix_acc_formato_empresas_formato_id'), table_name='acc_formato_empresas')
    op.drop_table('acc_formato_empresas')
    op.drop_index(op.f('ix_acc_cuentas_usuario_id'), table_name='acc_cuentas')
    op.drop_index(op.f('ix_acc_cuentas_formato_id'), table_name='acc_cuentas')
    op.drop_table('acc_cuentas')
    op.drop_table('acc_formatos')
    # ### end Alembic commands ###
