"""cdc system_id and module_id replace sistemas_afectados array

Revision ID: 5c0967de0571
Revises: a91f3d2e7c48
Create Date: 2026-09-25 19:57:51.816636

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '5c0967de0571'
down_revision: Union[str, None] = 'a91f3d2e7c48'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('control_cambios_detalle', sa.Column('system_id', sa.UUID(as_uuid=False), nullable=True))
    op.add_column('control_cambios_detalle', sa.Column('module_id', sa.UUID(as_uuid=False), nullable=True))
    op.create_foreign_key(None, 'control_cambios_detalle', 'ticket_modules', ['module_id'], ['id'])
    op.create_foreign_key(None, 'control_cambios_detalle', 'ticket_systems', ['system_id'], ['id'])
    op.drop_column('control_cambios_detalle', 'sistemas_afectados')
    op.drop_column('control_cambios_detalle', 'sistema_otro_detalle')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('control_cambios_detalle', sa.Column('sistema_otro_detalle', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.add_column('control_cambios_detalle', sa.Column('sistemas_afectados', postgresql.ARRAY(sa.VARCHAR()), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'control_cambios_detalle', type_='foreignkey')
    op.drop_constraint(None, 'control_cambios_detalle', type_='foreignkey')
    op.drop_column('control_cambios_detalle', 'module_id')
    op.drop_column('control_cambios_detalle', 'system_id')
    # ### end Alembic commands ###
