"""add control_cambios_avances

Revision ID: aa6f45a22bb9
Revises: d4f2b8c1a6e7
Create Date: 2026-09-30 02:37:52.112482

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'aa6f45a22bb9'
down_revision: Union[str, None] = 'd4f2b8c1a6e7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('control_cambios_avances',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('incident_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('rt_id', sa.String(length=20), nullable=True),
    sa.Column('estado', sa.String(length=15), nullable=True),
    sa.Column('horas', sa.Float(), nullable=True),
    sa.Column('comentario', sa.Text(), nullable=True),
    sa.Column('anexos', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('autor_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('autor_nombre', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['incident_id'], ['incidents.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_control_cambios_avances_incident_id'), 'control_cambios_avances', ['incident_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_control_cambios_avances_incident_id'), table_name='control_cambios_avances')
    op.drop_table('control_cambios_avances')
    # ### end Alembic commands ###
