"""add cdc clasificacion

Revision ID: b748727f9049
Revises: 2b284ada4d9e
Create Date: 2026-09-29 21:11:36.649699

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b748727f9049'
down_revision: Union[str, None] = '2b284ada4d9e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('control_cambios_detalle', sa.Column('clasificacion', sa.String(length=10), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('control_cambios_detalle', 'clasificacion')
    # ### end Alembic commands ###
