"""add control_cambios_documentos

Revision ID: b9f145fc7fb8
Revises: b748727f9049
Create Date: 2026-09-29 21:43:49.744482

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'b9f145fc7fb8'
down_revision: Union[str, None] = 'b748727f9049'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('control_cambios_documentos',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('incident_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('tipo', sa.String(length=30), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('estado', sa.String(length=15), nullable=False),
    sa.Column('origen', sa.String(length=15), nullable=False),
    sa.Column('datos', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('nombre', sa.String(length=255), nullable=True),
    sa.Column('object_key', sa.String(length=500), nullable=True),
    sa.Column('mime_type', sa.String(length=100), nullable=True),
    sa.Column('creado_por', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('creado_por_nombre', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['incident_id'], ['incidents.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_control_cambios_documentos_incident_id'), 'control_cambios_documentos', ['incident_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_control_cambios_documentos_incident_id'), table_name='control_cambios_documentos')
    op.drop_table('control_cambios_documentos')
    # ### end Alembic commands ###
