"""init incidencias tables

Revision ID: e31e3edfb865
Revises: 
Create Date: 2026-09-15 21:21:54.790938

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e31e3edfb865'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('folio_counters',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('prefix', sa.String(length=3), nullable=False),
    sa.Column('family_clave', sa.String(length=4), nullable=False),
    sa.Column('last_number', sa.Integer(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('prefix', 'family_clave', name='uq_folio_counters_prefix_family')
    )
    op.create_table('incidencias_settings',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('key', sa.String(length=100), nullable=False),
    sa.Column('value', sa.String(length=255), nullable=False),
    sa.Column('updated_by', sa.UUID(as_uuid=False), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('key')
    )
    op.create_table('ticket_severities',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('code', sa.String(length=4), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('response_sla_minutes', sa.Integer(), nullable=False),
    sa.Column('resolution_sla_hours', sa.Integer(), nullable=False),
    sa.Column('is_24_7', sa.Boolean(), nullable=False),
    sa.Column('rca_mandatory', sa.Boolean(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_table('ticket_systems',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('ticket_modules',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('system_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['system_id'], ['ticket_systems.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('system_id', 'name', name='uq_ticket_modules_system_name')
    )
    op.create_table('incidents',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('folio', sa.String(length=15), nullable=False),
    sa.Column('title', sa.String(length=150), nullable=False),
    sa.Column('company_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('requester_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('requester_name', sa.String(length=255), nullable=False),
    sa.Column('requester_phone', sa.String(length=20), nullable=True),
    sa.Column('requester_puesto', sa.String(length=255), nullable=True),
    sa.Column('requester_area', sa.String(length=255), nullable=True),
    sa.Column('requester_company_name', sa.String(length=255), nullable=False),
    sa.Column('system_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('module_id', sa.UUID(as_uuid=False), nullable=True),
    sa.Column('reported_type', sa.String(length=20), nullable=True),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('severity_reported_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('severity_validated_id', sa.UUID(as_uuid=False), nullable=True),
    sa.Column('assigned_team', sa.String(length=30), nullable=True),
    sa.Column('assigned_to_user_id', sa.UUID(as_uuid=False), nullable=True),
    sa.Column('attention_level', sa.String(length=5), nullable=True),
    sa.Column('first_response_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('sla_response_limit', sa.DateTime(timezone=True), nullable=True),
    sa.Column('sla_resolution_limit', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_sla_breached', sa.Boolean(), nullable=False),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('resolution_type', sa.String(length=20), nullable=True),
    sa.Column('reopen_window_expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('reopened_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('reopen_count', sa.Integer(), nullable=False),
    sa.Column('related_incident_id', sa.UUID(as_uuid=False), nullable=True),
    sa.Column('escalated_to', sa.String(length=30), nullable=False),
    sa.Column('escalated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('rca_text', sa.Text(), nullable=True),
    sa.Column('rca_due_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('closed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.Enum('en_backlog', 'asignado', 'en_atencion', 'escalado', 'resuelto', 'cerrado', name='incident_status_enum'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['module_id'], ['ticket_modules.id'], ),
    sa.ForeignKeyConstraint(['related_incident_id'], ['incidents.id'], ),
    sa.ForeignKeyConstraint(['severity_reported_id'], ['ticket_severities.id'], ),
    sa.ForeignKeyConstraint(['severity_validated_id'], ['ticket_severities.id'], ),
    sa.ForeignKeyConstraint(['system_id'], ['ticket_systems.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('folio')
    )
    op.create_table('system_specialists',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('system_id', sa.UUID(as_uuid=False), nullable=True),
    sa.Column('module_id', sa.UUID(as_uuid=False), nullable=True),
    sa.Column('team_type', sa.String(length=30), nullable=False),
    sa.Column('specialist_user_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['module_id'], ['ticket_modules.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['system_id'], ['ticket_systems.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('incident_activity_log',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('incident_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('action', sa.String(length=50), nullable=False),
    sa.Column('performed_by', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('performed_by_name', sa.String(length=255), nullable=False),
    sa.Column('performed_by_role', sa.String(length=100), nullable=False),
    sa.Column('performed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('user_agent', sa.String(length=255), nullable=True),
    sa.Column('company_id', sa.UUID(as_uuid=False), nullable=True),
    sa.Column('module_slug', sa.String(length=100), nullable=False),
    sa.Column('detail', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['incident_id'], ['incidents.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('incident_attachments',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('incident_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('attachment_type', sa.Enum('evidencia_reporte', 'evidencia_resolucion', name='incident_attachment_type_enum'), nullable=False),
    sa.Column('reopen_cycle', sa.Integer(), nullable=False),
    sa.Column('object_key', sa.String(length=500), nullable=False),
    sa.Column('bucket', sa.String(length=100), nullable=False),
    sa.Column('mime_type', sa.String(length=100), nullable=False),
    sa.Column('size_bytes', sa.BigInteger(), nullable=False),
    sa.Column('uploaded_by', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('uploaded_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['incident_id'], ['incidents.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('incident_resolution_tokens',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('incident_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('token', sa.String(length=128), nullable=False),
    sa.Column('created_for_user_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('used_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['incident_id'], ['incidents.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('token')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('incident_resolution_tokens')
    op.drop_table('incident_attachments')
    op.drop_table('incident_activity_log')
    op.drop_table('system_specialists')
    op.drop_table('incidents')
    op.drop_table('ticket_modules')
    op.drop_table('ticket_systems')
    op.drop_table('ticket_severities')
    op.drop_table('incidencias_settings')
    op.drop_table('folio_counters')
    # ### end Alembic commands ###
