"""add presentacion to acc_formatos

Revision ID: e6e9c81e9ba2
Revises: 4e832b89cab4
Create Date: 2026-09-30 23:04:31.715157

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'e6e9c81e9ba2'
down_revision: Union[str, None] = '4e832b89cab4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('acc_formatos', sa.Column('presentacion', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('acc_formatos', 'presentacion')
    # ### end Alembic commands ###
