"""add control_cambios_detalle table, nullable system/severity

Revision ID: fcd35a61ecfe
Revises: 7c2a91f4d8b3
Create Date: 2026-09-25 03:25:49.784943

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'fcd35a61ecfe'
down_revision: Union[str, None] = '7c2a91f4d8b3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('control_cambios_detalle',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('incident_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('sistemas_afectados', postgresql.ARRAY(sa.String()), nullable=False),
    sa.Column('sistema_otro_detalle', sa.String(length=255), nullable=True),
    sa.Column('area_departamento', sa.String(length=150), nullable=False),
    sa.Column('tipo_solicitud', sa.String(length=30), nullable=False),
    sa.Column('justificacion', sa.Text(), nullable=False),
    sa.Column('impacto_si_no_se_realiza', sa.String(length=10), nullable=False),
    sa.Column('urgencia_solicitada', sa.String(length=10), nullable=False),
    sa.Column('fecha_requerida', sa.Date(), nullable=True),
    sa.Column('comentarios_adicionales', sa.Text(), nullable=True),
    sa.Column('solicitud_pdf_object_key', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['incident_id'], ['incidents.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('incident_id')
    )
    op.alter_column('incidents', 'system_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.alter_column('incidents', 'severity_reported_id',
               existing_type=sa.UUID(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('incidents', 'severity_reported_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.alter_column('incidents', 'system_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.drop_table('control_cambios_detalle')
    # ### end Alembic commands ###
