"""add docusign audit events table

Revision ID: e405fc84ade0
Revises: e7f1a2b3c4d5
Create Date: 2026-07-31 02:35:42.365144

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e405fc84ade0'
down_revision: Union[str, Sequence[str], None] = 'e7f1a2b3c4d5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('envelope_docusign_audit_events',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('envelope_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('docusign_envelope_id', sa.String(length=100), nullable=False),
    sa.Column('log_time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('source', sa.String(length=20), nullable=True),
    sa.Column('user_name', sa.String(length=255), nullable=True),
    sa.Column('docusign_user_id', sa.String(length=100), nullable=True),
    sa.Column('action', sa.String(length=100), nullable=True),
    sa.Column('message', sa.Text(), nullable=True),
    sa.Column('envelope_status', sa.String(length=50), nullable=True),
    sa.Column('client_ip', sa.String(length=45), nullable=True),
    sa.Column('information', sa.Text(), nullable=True),
    sa.Column('information_localized', sa.JSON(), nullable=True),
    sa.Column('geo_location', sa.String(length=255), nullable=True),
    sa.Column('language', sa.String(length=50), nullable=True),
    sa.Column('raw_event', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['envelope_id'], ['envelopes.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # NOTA: se removieron aqui los drop_index de indices preexistentes
    # (envelope_signers, envelope_signing_tokens, envelopes) que el
    # autogenerate detecto de mas por desfase con el modelo actual —
    # no tienen relacion con esta migracion y no deben tocarse.
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('envelope_docusign_audit_events')
    # ### end Alembic commands ###
