"""initial schema contract requests

Revision ID: fd194ef42a01
Revises: 
Create Date: 2026-05-07 18:28:39.565847

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fd194ef42a01'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('contract_types',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('slug', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('sla_business_days', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_by', sa.UUID(as_uuid=False), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('slug')
    )
    op.create_table('folio_sequences',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('last_sequence', sa.Integer(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('year')
    )
    op.create_table('contract_requests',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('folio', sa.String(length=20), nullable=False),
    sa.Column('company_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('company_name', sa.String(length=255), nullable=False),
    sa.Column('requested_by_user_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('requested_by_name', sa.String(length=255), nullable=False),
    sa.Column('requested_by_email', sa.String(length=255), nullable=False),
    sa.Column('contract_type_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('contract_type_name', sa.String(length=255), nullable=False),
    sa.Column('assigned_lawyer_id', sa.UUID(as_uuid=False), nullable=True),
    sa.Column('assigned_lawyer_name', sa.String(length=255), nullable=True),
    sa.Column('assigned_lawyer_email', sa.String(length=255), nullable=True),
    sa.Column('assigned_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.Enum('borrador', 'pendiente_legal', 'pendiente_cliente', 'en_revision_legal', 'en_firmas', 'firmado_parcial', 'completado', 'rechazado', name='contract_status_enum'), nullable=False),
    sa.Column('form_data', sa.JSON(), nullable=True),
    sa.Column('counterparty_name', sa.String(length=255), nullable=True),
    sa.Column('counterparty_email', sa.String(length=255), nullable=True),
    sa.Column('is_open_request', sa.Boolean(), nullable=False),
    sa.Column('open_request_description', sa.Text(), nullable=True),
    sa.Column('submitted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('sla_due_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('sla_closed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_sla_breached', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_by', sa.UUID(as_uuid=False), nullable=True),
    sa.ForeignKeyConstraint(['contract_type_id'], ['contract_types.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('folio')
    )
    op.create_table('contract_type_attachment_defs',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('contract_type_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_required', sa.Boolean(), nullable=False),
    sa.Column('display_order', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['contract_type_id'], ['contract_types.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('contract_type_fields',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('contract_type_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('label', sa.String(length=255), nullable=False),
    sa.Column('field_key', sa.String(length=100), nullable=False),
    sa.Column('field_type', sa.String(length=50), nullable=False),
    sa.Column('placeholder', sa.String(length=255), nullable=True),
    sa.Column('options', sa.JSON(), nullable=True),
    sa.Column('is_required', sa.Boolean(), nullable=False),
    sa.Column('display_order', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['contract_type_id'], ['contract_types.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('lawyer_assignments',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('lawyer_user_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('lawyer_name', sa.String(length=255), nullable=False),
    sa.Column('lawyer_email', sa.String(length=255), nullable=False),
    sa.Column('contract_type_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('assigned_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('assigned_by', sa.UUID(as_uuid=False), nullable=False),
    sa.ForeignKeyConstraint(['contract_type_id'], ['contract_types.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('contract_activity_logs',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('contract_request_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('action', sa.String(length=100), nullable=False),
    sa.Column('performed_by_user_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('performed_by_name', sa.String(length=255), nullable=False),
    sa.Column('performed_by_role', sa.String(length=100), nullable=False),
    sa.Column('performed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('detail', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['contract_request_id'], ['contract_requests.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('contract_attachments',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('contract_request_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('attachment_def_id', sa.UUID(as_uuid=False), nullable=True),
    sa.Column('original_name', sa.String(length=255), nullable=False),
    sa.Column('stored_name', sa.String(length=255), nullable=False),
    sa.Column('object_key', sa.String(length=500), nullable=False),
    sa.Column('bucket', sa.String(length=100), nullable=False),
    sa.Column('mime_type', sa.String(length=100), nullable=False),
    sa.Column('extension', sa.String(length=20), nullable=False),
    sa.Column('size_bytes', sa.BigInteger(), nullable=False),
    sa.Column('checksum', sa.String(length=64), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('uploaded_by_user_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('uploaded_by_name', sa.String(length=255), nullable=False),
    sa.Column('uploaded_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_by', sa.UUID(as_uuid=False), nullable=True),
    sa.ForeignKeyConstraint(['attachment_def_id'], ['contract_type_attachment_defs.id'], ),
    sa.ForeignKeyConstraint(['contract_request_id'], ['contract_requests.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('contract_comments',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('contract_request_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('author_user_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('author_name', sa.String(length=255), nullable=False),
    sa.Column('author_role', sa.String(length=100), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('is_internal', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('edited_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['contract_request_id'], ['contract_requests.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('contract_form_snapshots',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('contract_request_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('form_data', sa.JSON(), nullable=False),
    sa.Column('submitted_by_user_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('submitted_by_name', sa.String(length=255), nullable=False),
    sa.Column('submitted_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['contract_request_id'], ['contract_requests.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('contract_status_logs',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('contract_request_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('from_status', sa.String(length=50), nullable=True),
    sa.Column('to_status', sa.String(length=50), nullable=False),
    sa.Column('changed_by_user_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('changed_by_name', sa.String(length=255), nullable=False),
    sa.Column('changed_by_role', sa.String(length=100), nullable=False),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('changed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.ForeignKeyConstraint(['contract_request_id'], ['contract_requests.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('contract_time_tracking',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('contract_request_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('responsible_user_id', sa.UUID(as_uuid=False), nullable=True),
    sa.Column('responsible_user_name', sa.String(length=255), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('ended_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('duration_minutes', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['contract_request_id'], ['contract_requests.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('contract_attachment_logs',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('attachment_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('contract_request_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('action', sa.String(length=50), nullable=False),
    sa.Column('performed_by_user_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('performed_by_name', sa.String(length=255), nullable=False),
    sa.Column('performed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('detail', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['attachment_id'], ['contract_attachments.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('contract_attachment_logs')
    op.drop_table('contract_time_tracking')
    op.drop_table('contract_status_logs')
    op.drop_table('contract_form_snapshots')
    op.drop_table('contract_comments')
    op.drop_table('contract_attachments')
    op.drop_table('contract_activity_logs')
    op.drop_table('lawyer_assignments')
    op.drop_table('contract_type_fields')
    op.drop_table('contract_type_attachment_defs')
    op.drop_table('contract_requests')
    op.drop_table('folio_sequences')
    op.drop_table('contract_types')
    # ### end Alembic commands ###
